=== zintljs/zintl/examples/svelte-basic/zintl/.schemas/src/App.svelte.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "Connect with us": {
      "type": "string"
    },
    "Documentation": {
      "type": "string"
    },
    "Edit <code>src/App.svelte</code> and save to test <code>HMR</code>": {
      "type": "string"
    },
    "Explore Vite": {
      "type": "string"
    },
    "Get started": {
      "type": "string"
    },
    "Join the Vite community": {
      "type": "string"
    },
    "Learn more": {
      "type": "string"
    },
    "Svelte logo": {
      "type": "string"
    },
    "Vite logo": {
      "type": "string"
    },
    "Your questions, answered": {
      "type": "string"
    }
  },
  "required": [
    "Connect with us",
    "Documentation",
    "Edit <code>src/App.svelte</code> and save to test <code>HMR</code>",
    "Explore Vite",
    "Get started",
    "Join the Vite community",
    "Learn more",
    "Svelte logo",
    "Vite logo",
    "Your questions, answered"
  ],
  "additionalProperties": false
}

=== zintljs/zintl/examples/svelte-ssr/zintl/src/App.svelte.ar.json
{
  "$schema": "../.schemas/src/App.svelte.schema.json",
  "Connect with us": "تواصل معنا",
  "Documentation": "التوثيق",
  "Edit <code>src/App.svelte</code> and save to test <code>HMR</code>": "عدل <code>src/App.svelte</code> واحفظه لاختبار <code>HMR</code>",
  "Explore Vite": "استكشف فيت",
  "Get started": "البدء",
  "Join the Vite community": "انضم إلى مجتمع فيت",
  "Learn more": "تعلم المزيد",
  "Svelte logo": "شعار سفتلي",
  "Vite logo": "شعار فيت",
  "Your questions, answered": "تمت الإجابة على أسئلتك"
}

=== zintljs/zintl/examples/svelte-basic/zintl/src/App.svelte.es.json
{
  "$schema": "../.schemas/src/App.svelte.schema.json",
  "Connect with us": "Conéctate con nosotros",
  "Documentation": "Documentación",
  "Edit <code>src/App.svelte</code> and save to test <code>HMR</code>": "Edite <code>src/App.svelte</code> y guarde para probar <code>HMR</code>",
  "Explore Vite": "Explorar Vite",
  "Get started": "Comenzar",
  "Join the Vite community": "Únete a la comunidad de Vite",
  "Learn more": "Aprender más",
  "Svelte logo": "Logo de Svelte",
  "Vite logo": "Logo de Vite",
  "Your questions, answered": "Tus preguntas, respondidas"
}

=== zintljs/zintl/examples/svelte-basic/zintl/src/App.svelte.zh.json
{
  "$schema": "../.schemas/src/App.svelte.schema.json",
  "Connect with us": "与我们联系",
  "Documentation": "文档",
  "Edit <code>src/App.svelte</code> and save to test <code>HMR</code>": "编辑 <code>src/App.svelte</code> 并保存以测试 <code>HMR</code>",
  "Explore Vite": "探索 Vite",
  "Get started": "开始",
  "Join the Vite community": "加入 Vite 社区",
  "Learn more": "了解更多",
  "Svelte logo": "Svelte 图标",
  "Vite logo": "Vite 图标",
  "Your questions, answered": "您的问题已解答"
}
