=== zintljs/zintl/examples/rsbuild-vue-spa/src/locales/.schemas/src/components/HelloWorld.vue.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "Count is {count}": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        }
      ],
      "description": "Variables: {count}"
    },
    "Edit <code>src/components/HelloWorld.vue</code> and save to test <code>HMR</code>": {
      "type": "string"
    },
    "Read the guide": {
      "type": "string"
    },
    "Rsbuild with Vue": {
      "type": "string"
    },
    "Start building amazing things with Rsbuild.": {
      "type": "string"
    }
  },
  "required": [
    "Count is {count}",
    "Edit <code>src/components/HelloWorld.vue</code> and save to test <code>HMR</code>",
    "Read the guide",
    "Rsbuild with Vue",
    "Start building amazing things with Rsbuild."
  ],
  "additionalProperties": false
}

=== zintljs/zintl/examples/rsbuild-vue-spa/src/locales/src/components/HelloWorld.vue.es.json
{
  "$schema": "../../.schemas/src/components/HelloWorld.vue.schema.json",
  "Count is {count}": "La cuenta es {count}",
  "Edit <code>src/components/HelloWorld.vue</code> and save to test <code>HMR</code>": "Edita <code>src/components/HelloWorld.vue</code> y guarda para probar <code>HMR</code>",
  "Read the guide": "Leer la guía",
  "Rsbuild with Vue": "Rsbuild con Vue",
  "Start building amazing things with Rsbuild.": "Empieza a construir cosas increíbles con Rsbuild."
}

=== zintljs/zintl/examples/rsbuild-vue-spa/src/locales/src/components/HelloWorld.vue.zh.json
{
  "$schema": "../../.schemas/src/components/HelloWorld.vue.schema.json",
  "Count is {count}": "计数为 {count}",
  "Edit <code>src/components/HelloWorld.vue</code> and save to test <code>HMR</code>": "编辑 <code>src/components/HelloWorld.vue</code> 并保存以测试 <code>HMR</code>",
  "Read the guide": "阅读指南",
  "Rsbuild with Vue": "Rsbuild 搭配 Vue",
  "Start building amazing things with Rsbuild.": "使用 Rsbuild 开始构建精彩的应用。"
}
