=== zintljs/zintl/examples/vue-mpa/zintl/.schemas/src/components/AboutWorld.vue.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "About Zintl MPA": {
      "type": "string"
    },
    "Bluesky": {
      "type": "string"
    },
    "Connect with us": {
      "type": "string"
    },
    "Discord": {
      "type": "string"
    },
    "Documentation": {
      "type": "string"
    },
    "Explore Vite": {
      "type": "string"
    },
    "GitHub": {
      "type": "string"
    },
    "Go back Home": {
      "type": "string"
    },
    "Join the Vite community": {
      "type": "string"
    },
    "Learn more": {
      "type": "string"
    },
    "This page demonstrates clean MPA routing and fully isolated hydration cycles in Vue.": {
      "type": "string"
    },
    "Vite logo": {
      "type": "string"
    },
    "Vue logo": {
      "type": "string"
    },
    "X.com": {
      "type": "string"
    },
    "Your questions, answered": {
      "type": "string"
    }
  },
  "required": [
    "About Zintl MPA",
    "Bluesky",
    "Connect with us",
    "Discord",
    "Documentation",
    "Explore Vite",
    "GitHub",
    "Go back Home",
    "Join the Vite community",
    "Learn more",
    "This page demonstrates clean MPA routing and fully isolated hydration cycles in Vue.",
    "Vite logo",
    "Vue logo",
    "X.com",
    "Your questions, answered"
  ],
  "additionalProperties": false
}

=== zintljs/zintl/examples/vue-mpa/zintl/src/components/AboutWorld.vue.zh.json
{
  "$schema": "../../.schemas/src/components/AboutWorld.vue.schema.json",
  "About Zintl MPA": "关于 Zintl MPA",
  "Bluesky": "Bluesky",
  "Connect with us": "与我们联系",
  "Discord": "Discord",
  "Documentation": "文档",
  "Explore Vite": "探索 Vite",
  "GitHub": "GitHub",
  "Go back Home": "返回首页",
  "Join the Vite community": "加入 Vite 社区",
  "Learn more": "了解更多",
  "This page demonstrates clean MPA routing and fully isolated hydration cycles in Vue.": "此页面展示了 Vue 中整洁的 MPA 路由和完全隔离的补水生命周期。",
  "Vite logo": "Vite 图标",
  "Vue logo": "Vue 图标",
  "X.com": "X.com",
  "Your questions, answered": "你的问题，已解答"
}

=== zintljs/zintl/examples/vue-mpa/zintl/src/components/AboutWorld.vue.ar.json
{
  "$schema": "../../.schemas/src/components/AboutWorld.vue.schema.json",
  "About Zintl MPA": "حول Zintl MPA",
  "Bluesky": "بلو سكاي",
  "Connect with us": "تواصل معنا",
  "Discord": "ديسكورد",
  "Documentation": "التوثيق",
  "Explore Vite": "استكشف فيت",
  "GitHub": "غيت هاب",
  "Go back Home": "الرجوع إلى الرئيسية",
  "Join the Vite community": "انضم إلى مجتمع فيت",
  "Learn more": "تعلم المزيد",
  "This page demonstrates clean MPA routing and fully isolated hydration cycles in Vue.": "توضح هذه الصفحة توجيه MPA النظيف ودورات إماهة معزولة تماماً في Vue.",
  "Vite logo": "شعار فيت",
  "Vue logo": "شعار فيو",
  "X.com": "إكس.كوم",
  "Your questions, answered": "تمت الإجابة على أسئلتك"
}
