=== zintljs/zintl/examples/website/zintl/.schemas/src/components/SiteSearch.vue.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "Nothing matches that.": {
      "type": "string"
    },
    "Search": {
      "type": "string"
    },
    "Search the documentation": {
      "type": "string"
    },
    "Type to search the pages in this language.": {
      "type": "string"
    }
  },
  "required": [
    "Nothing matches that.",
    "Search",
    "Search the documentation",
    "Type to search the pages in this language."
  ],
  "additionalProperties": false
}

=== zintljs/zintl/examples/website/zintl/src/components/SiteSearch.vue.es.json
{
  "$schema": "../../.schemas/src/components/SiteSearch.vue.schema.json",
  "Nothing matches that.": "Nada coincide con eso.",
  "Search": "Buscar",
  "Search the documentation": "Buscar en la documentación",
  "Type to search the pages in this language.": "Escribe para buscar en las páginas de este idioma."
}
