=== zintljs/zintl/examples/vue-basic/zintl/.schemas/src/components/HelloWorld.vue.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "Bluesky": {
      "type": "string"
    },
    "Connect with us": {
      "type": "string"
    },
    "Count is {count}": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        }
      ],
      "description": "Variables: {count}"
    },
    "Discord": {
      "type": "string"
    },
    "Documentation": {
      "type": "string"
    },
    "Edit <code>src/App.vue</code> and save to test <code>HMR</code>": {
      "type": "string"
    },
    "Explore Vite": {
      "type": "string"
    },
    "Get started": {
      "type": "string"
    },
    "GitHub": {
      "type": "string"
    },
    "Join the Vite community": {
      "type": "string"
    },
    "Learn more": {
      "type": "string"
    },
    "Vite logo": {
      "type": "string"
    },
    "Vue logo": {
      "type": "string"
    },
    "X.com": {
      "type": "string"
    },
    "Your questions, answered": {
      "type": "string"
    }
  },
  "required": [
    "Bluesky",
    "Connect with us",
    "Count is {count}",
    "Discord",
    "Documentation",
    "Edit <code>src/App.vue</code> and save to test <code>HMR</code>",
    "Explore Vite",
    "Get started",
    "GitHub",
    "Join the Vite community",
    "Learn more",
    "Vite logo",
    "Vue logo",
    "X.com",
    "Your questions, answered"
  ],
  "additionalProperties": false
}

=== zintljs/zintl/examples/vue-ssr/zintl/src/components/HelloWorld.vue.es.json
{
  "$schema": "../../.schemas/src/components/HelloWorld.vue.schema.json",
  "Bluesky": "Bluesky",
  "Connect with us": "Conéctate con nosotros",
  "Count is {count}": "El recuento es { count }",
  "Discord": "Discord",
  "Documentation": "Documentación",
  "Edit <code>src/App.vue</code> and save to test <code>HMR</code>": "Edita <code>src/App.vue</code> y guarda para probar <code>HMR</code>",
  "Explore Vite": "Explorar Vite",
  "Get started": "Empezar",
  "GitHub": "GitHub",
  "Join the Vite community": "Únete a la comunidad de Vite",
  "Learn more": "Aprende más",
  "Vite logo": "Logotipo de Vite",
  "Vue logo": "Logotipo de Vue",
  "X.com": "X.com",
  "Your questions, answered": "Tus preguntas, respondidas"
}

=== zintljs/zintl/examples/vue-basic/zintl/src/components/HelloWorld.vue.ar.json
{
  "$schema": "../../.schemas/src/components/HelloWorld.vue.schema.json",
  "Bluesky": "بلو سكاي",
  "Connect with us": "تواصل معنا",
  "Count is {count}": "العدد هو { count }",
  "Discord": "ديسكورد",
  "Documentation": "التوثيق",
  "Edit <code>src/App.vue</code> and save to test <code>HMR</code>": "قم بتعديل <code>src/App.vue</code> واحفظه لاختبار <code>HMR</code>",
  "Explore Vite": "استكشف فيت",
  "Get started": "البدء",
  "GitHub": "غيت هاب",
  "Join the Vite community": "انضم إلى مجتمع فيت",
  "Learn more": "تعلم المزيد",
  "Vite logo": "شعار فيت",
  "Vue logo": "شعار فيو",
  "X.com": "إكس.كوم",
  "Your questions, answered": "تمت الإجابة على أسئلتك"
}

=== zintljs/zintl/examples/vue-basic/zintl/src/components/HelloWorld.vue.zh.json
{
  "$schema": "../../.schemas/src/components/HelloWorld.vue.schema.json",
  "Bluesky": "Bluesky",
  "Connect with us": "与我们联系",
  "Count is {count}": "计数为 { count }",
  "Discord": "Discord",
  "Documentation": "文档",
  "Edit <code>src/App.vue</code> and save to test <code>HMR</code>": "编辑 <code>src/App.vue</code> 并保存以测试 <code>HMR</code>",
  "Explore Vite": "探索 Vite",
  "Get started": "开始",
  "GitHub": "GitHub",
  "Join the Vite community": "加入 Vite 社区",
  "Learn more": "了解更多",
  "Vite logo": "Vite 图标",
  "Vue logo": "Vue 图标",
  "X.com": "X.com",
  "Your questions, answered": "你的问题，已解答"
}
