=== zintljs/zintl/examples/preact-basic/zintl/.schemas/src/app.tsx.App.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "<img/> Explore Vite": {
      "type": "string"
    },
    "<img/> Learn more": {
      "type": "string"
    },
    "Connect with us": {
      "type": "string"
    },
    "Count is {count}": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        }
      ],
      "description": "Variables: {count}"
    },
    "Documentation": {
      "type": "string"
    },
    "Edit <code>src/app.tsx</code> and save to test <code>HMR</code>": {
      "type": "string"
    },
    "Get started": {
      "type": "string"
    },
    "Join the Vite community": {
      "type": "string"
    },
    "Preact logo": {
      "type": "string"
    },
    "Vite logo": {
      "type": "string"
    },
    "Your questions, answered": {
      "type": "string"
    }
  },
  "required": [
    "<img/> Explore Vite",
    "<img/> Learn more",
    "Connect with us",
    "Count is {count}",
    "Documentation",
    "Edit <code>src/app.tsx</code> and save to test <code>HMR</code>",
    "Get started",
    "Join the Vite community",
    "Preact logo",
    "Vite logo",
    "Your questions, answered"
  ],
  "additionalProperties": false
}

=== zintljs/zintl/examples/preact-basic/zintl/src/app.tsx.App.es.json
{
  "$schema": "../.schemas/src/app.tsx.App.schema.json",
  "<img/> Explore Vite": "<img/> Explorar Vite",
  "<img/> Learn more": "<img/> Aprender más",
  "Connect with us": "Conéctate con nosotros",
  "Count is {count}": "El recuento es {count}",
  "Documentation": "Documentación",
  "Edit <code>src/app.tsx</code> and save to test <code>HMR</code>": "Edita <code>src/app.tsx</code> y guarda para probar <code>HMR</code>",
  "Get started": "Empezar",
  "Join the Vite community": "Únete a la comunidad de Vite",
  "Preact logo": "Logotipo de Preact",
  "Vite logo": "Logotipo de Vite",
  "Your questions, answered": "Tus preguntas, respondidas"
}

=== zintljs/zintl/examples/preact-basic/zintl/src/app.tsx.App.ar.json
{
  "$schema": "../.schemas/src/app.tsx.App.schema.json",
  "<img/> Explore Vite": "<img/> استكشف فيت",
  "<img/> Learn more": "<img/> تعلم المزيد",
  "Connect with us": "تواصل معنا",
  "Count is {count}": "العدد هو {count}",
  "Documentation": "التوثيق",
  "Edit <code>src/app.tsx</code> and save to test <code>HMR</code>": "عدل <code>src/app.tsx</code> واحفظه لاختبار <code>HMR</code>",
  "Get started": "البدء",
  "Join the Vite community": "انضم إلى مجتمع فيت",
  "Preact logo": "شعار بريأكت",
  "Vite logo": "شعار فيت",
  "Your questions, answered": "تمت الإجابة على أسئلتك"
}

=== zintljs/zintl/examples/preact-basic/zintl/src/App.tsx.App.zh.json
{
  "$schema": "../.schemas/src/App.tsx.App.schema.json",
  "<img/> Explore Vite": "<img/> 探索 Vite",
  "<img/> Learn more": "<img/> 了解更多",
  "Connect with us": "与我们联系",
  "Count is {count}": "计数为 {count}",
  "Documentation": "文档",
  "Edit <code>src/app.tsx</code> and save to test <code>HMR</code>": "编辑 <code>src/app.tsx</code> 并保存以测试 <code>HMR</code>",
  "Get started": "开始",
  "Join the Vite community": "加入 Vite 社区",
  "Preact logo": "Preact 图标",
  "Vite logo": "Vite 图标",
  "Your questions, answered": "您的问题，已有解答"
}
