=== zintljs/zintl/tests/fixtures/rsbuild-spa/src/i18n/.schemas/translations.shared.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "Count is {counter}": {
      "additionalProperties": false,
      "description": "Variables: {counter}",
      "properties": {
        "ar": {
          "type": "string"
        },
        "es": {
          "type": "string"
        },
        "zh": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "Documentation": {
      "additionalProperties": false,
      "description": "",
      "properties": {
        "ar": {
          "type": "string"
        },
        "es": {
          "type": "string"
        },
        "zh": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "Edit <code>src/main.ts</code> and save to test <code>HMR</code>": {
      "additionalProperties": false,
      "description": "",
      "properties": {
        "ar": {
          "type": "string"
        },
        "es": {
          "type": "string"
        },
        "zh": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "Get started": {
      "additionalProperties": false,
      "description": "",
      "properties": {
        "ar": {
          "type": "string"
        },
        "es": {
          "type": "string"
        },
        "zh": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "Your questions, answered": {
      "additionalProperties": false,
      "description": "",
      "properties": {
        "ar": {
          "type": "string"
        },
        "es": {
          "type": "string"
        },
        "zh": {
          "type": "string"
        }
      },
      "type": "object"
    }
  },
  "required": [
    "Count is {counter}",
    "Documentation",
    "Edit <code>src/main.ts</code> and save to test <code>HMR</code>",
    "Get started",
    "Your questions, answered"
  ],
  "additionalProperties": false
}

=== zintljs/zintl/tests/fixtures/rsbuild-spa/src/i18n/translations.json
{
  "$schema": ".schemas/translations.shared.schema.json",
  "Count is {counter}": {
    "ar": "العدد هو {counter}",
    "es": "La cuenta es {counter}",
    "zh": "计数为 {counter}"
  },
  "Documentation": {
    "ar": "وثائق",
    "es": "Documentación",
    "zh": "文档"
  },
  "Edit <code>src/main.ts</code> and save to test <code>HMR</code>": {
    "ar": "عدّل <code>src/main.ts</code> واحفظ لاختبار <code>HMR</code>",
    "es": "Editar <code>src/main.ts</code> y guardar para probar <code>HMR</code>",
    "zh": "编辑 <code>src/main.ts</code> 并保存以测试 <code>HMR</code>"
  },
  "Get started": {
    "ar": "ابدأ الآن",
    "es": "Empezar",
    "zh": "开始使用"
  },
  "Your questions, answered": {
    "ar": "إجابات لأسئلتك",
    "es": "Tus preguntas, respondidas",
    "zh": "你的问题，已有答案"
  }
}
