=== zintljs/zintl/examples/rsbuild-vanilla-basic/src/i18n/.schemas/translations.shared.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "Count is {counter}": {
      "additionalProperties": false,
      "description": "Variables: {counter}",
      "properties": {
        "ar": {
          "type": "string"
        },
        "es": {
          "type": "string"
        },
        "zh": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "Edit <code>src/index.ts</code> and save to test <code>HMR</code>": {
      "additionalProperties": false,
      "description": "",
      "properties": {
        "ar": {
          "type": "string"
        },
        "es": {
          "type": "string"
        },
        "zh": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "Start building amazing things with Rsbuild.": {
      "additionalProperties": false,
      "description": "",
      "properties": {
        "ar": {
          "type": "string"
        },
        "es": {
          "type": "string"
        },
        "zh": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "Vanilla Rsbuild": {
      "additionalProperties": false,
      "description": "",
      "properties": {
        "ar": {
          "type": "string"
        },
        "es": {
          "type": "string"
        },
        "zh": {
          "type": "string"
        }
      },
      "type": "object"
    }
  },
  "required": [
    "Count is {counter}",
    "Edit <code>src/index.ts</code> and save to test <code>HMR</code>",
    "Start building amazing things with Rsbuild.",
    "Vanilla Rsbuild"
  ],
  "additionalProperties": false
}

=== zintljs/zintl/examples/rsbuild-vanilla-basic/src/i18n/translations.json
{
  "$schema": ".schemas/translations.shared.schema.json",
  "Count is {counter}": {
    "ar": "{counter, plural, zero {لم يبدأ العد بعد} one {العدد واحد} two {العدد اثنان} few {العدد {counter}} many {العدد {counter}} other {العدد {counter}}}",
    "es": "{counter, plural, =0 {Aún no has contado} one {La cuenta es uno} other {La cuenta es #}}",
    "zh": "{counter, plural, =0 {还没有开始计数} other {计数为 {counter}}}"
  },
  "Edit <code>src/index.ts</code> and save to test <code>HMR</code>": {
    "ar": "عدّل <code>src/index.ts</code> واحفظ لاختبار <code>HMR</code>",
    "es": "Edita <code>src/index.ts</code> y guarda para probar <code>HMR</code>",
    "zh": "编辑 <code>src/index.ts</code> 并保存以测试 <code>HMR</code>"
  },
  "Start building amazing things with Rsbuild.": {
    "ar": "ابدأ ببناء أشياء مذهلة مع Rsbuild.",
    "es": "Empieza a construir cosas increíbles con Rsbuild.",
    "zh": "使用 Rsbuild 开始构建精彩的应用。"
  },
  "Vanilla Rsbuild": {
    "ar": "Rsbuild الأساسي",
    "es": "Rsbuild con Vanilla",
    "zh": "原生 Rsbuild"
  }
}
